### ISSUE TITLE
Missing data and patchy replacements when trying to merge map data

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [gipsy-king/civmap-client#124]
Readme is missing instructions. I managed to get it working on my Vagrant box by installing imagemagik like so:

    sudo apt-get update
    sudo apt-get install imagemagick

I'll add this information to the readme shortly.

**Comment by RailsDev42** [comment]
I should also mention I've tried this on my Vagrant (Ubuntu 64) box and not had any better results. I'm using Python 2.7.10.

**Comment by RailsDev42** [comment]
In fact... I'm guessing it's this: http://www.imagemagick.org/script/binary-releases.php

Am I ok to use windows or do you tend to stick to linux for this work?

**Comment by RailsDev42** [comment]
Right, managed to get it working on my Vagrant box by installing imagemagik like so:

    sudo apt-get update
    sudo apt-get install imagemagick

I'll add this information to the readme shortly.

**Comment by RailsDev42** [comment]
I've got this to work but only by forcing the merge to overwrite older map data with:

    python merge.py my-data-dir over

It doesn't seem to recognise that the journeymap tiles are newer than the existing map data.

Also, map data seems to be missing - I've got the old map data for Venice here. Is the repository out of date with the live version?

**Comment by RailsDev42** [comment]
TODO: Add some more detailed instructions in the Readme, including Git tips.

**Comment by benjajaja** [comment]
@RailsDev42 yea it'd be a good idea to add everything that's missing to the readme.

The issue with data not getting added is probably because when you clone the repo, all the timestamps are fresh and the merge.py of data/ thinks the data you are merging is older. So only I could do proper merges with correct timestamps.

For the voxelmap merger here https://github.com/gipsy-king/civcraft-voxelmap/blob/master/merge.py you can see that I added a timestamp index file to be committed too, that way the age of the data is always correct. This feature should probably be copied over to journeymap's merge.py.

**Comment by CodingMonkeyXYZ** [comment]
Yeah that sounds good. I figured it was something like that, which is why I used the 'over' option. I figured in this case it was ok because my data is pretty up-to-date. I wiped my map files before I began collecting each different part of the map too.

I think a timstamp index would be a good solution though.
