### ISSUE TITLE
Title Corrections

### ISSUE THREAD

**Issue by markrwells** [gipsy-king/civmap-client#31]
We submitted some city names the other day for SPQR. Its possible (most likely) we did not understand the definition between city and town.  Looking at the map now, Carthage and Athens should not be listed as a nation/city with the circle and name overlaid when the map is zoomed out.  In this respect they should be towns. 

Also, when the changes were being made, the SPQR label that was there has been removed.  This again was most likely because we labeled ROMA as a city instead of a town.  ROMA is city WITHIN the Nation of SPQR so SPQR should be the label that you see overlaid on the circle when the map is zoomed out.  

Please change the classifications of the cities to towns and please add the following label back to the map:

City/Nation: SPQR
-11920, -8730
/r/civcraftroma

**Comment by gipsy-king** [comment]
The problem is that so far there is no unambiguous concept of nation or state in civcraft. The lines between cities, towns, nations, states, empires, regions, districts, associations and alliances are very unclear and subjective.

So, so far, on the map there are cities, towns, and land claims. I don't want to decide on a concept of nation right now. This means that cities represent nations in some degree, as city states or capital cities. This is accurate for most cases in civcraft, but sadly not all.
